"""empty message

Revision ID: 53290ac01bea
Revises: b1ddc0a15c26
Create Date: 2026-02-23 14:53:11.648895

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '53290ac01bea'
down_revision: Union[str, Sequence[str], None] = 'b1ddc0a15c26'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user_profile', 'profile_image',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user_profile', 'profile_image',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###
